#!/bin/bash

/opt/conda/bin/python3

python -m nltk.downloader stopwords wordnet

url=https://raw.githubusercontent.com/ithaka/tdm-notebooks/41cfb568e4e4ea57920141d602b6a3d46ed88b0a/tdm_client.py

wget $url

exec "$@"